name: base
channels:
  - conda-forge
  - chuckpr
dependencies:
  - r-base
  - r-tidymodels
  - r-tidyverse
  - r-irkernel
  - r-palmerpenguins
  - r-islr2
  - jupyterlab-git
  - r-moderndive
  - nbgitpuller
  - pandas
  - scikit-learn
  - plotnine
  - altair
