name: base
channels:
  - conda-forge
  - chuckpr
dependencies:
  - r-base=4.3.3
  - r-tidymodels
  - r-tidyverse
  - r-irkernel
  - r-palmerpenguins
  - r-islr2
  - jupyterlab-git
  - r-moderndive
  - nbgitpuller
